// sidebars.js
const sidebars = {
  docsSidebar: [
    {
      type: 'category',
      label: 'О проекте',
      link: { type: 'doc', id: 'about/project' },
      items: [
        'about/project',
        'about/collections',
        'about/collections/pervye-shagi',
        'about/interactive',
        'about/author',
        'about/license',
        'about/manifest',
        {
          type: 'category',
          label: 'Как устроена Вселенная IT',
          link: { type: 'doc', id: 'about/kak-ustroena-vselennaya-it/index' },
          items: [
            {
              type: 'autogenerated',
              dirName: 'about/kak-ustroena-vselennaya-it',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Энциклопедия',
      link: { type: 'doc', id: 'encyclopedia/intro' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'encyclopedia',
        },
      ],
    },
    {
      type: 'link',
      label: 'Инструменты',
      href: 'https://tools.spirzen.ru/tools/intro',
    },
    {
      type: 'link',
      label: 'Глоссарий',
      href: 'https://terms.spirzen.ru/glossary/intro',
    },
    {
      type: 'link',
      label: 'Лаборатория',
      href: 'https://lab.spirzen.ru/lab/intro',
    },
    {
      type: 'category',
      label: 'Контекст',
      link: { type: 'doc', id: 'context/intro' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'context',
        },
      ],
    },
    {
      type: 'category',
      label: 'Философия',
      link: { type: 'doc', id: 'philosophy/intro' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'philosophy',
        },
      ],
    },
    {
      type: 'doc',
      id: 'toc',
      label: 'Общее содержание',
    },
  ],
};

export default sidebars;