/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [
    {
      type: 'category',
      label: 'О проекте',
      items: ['about/contact', 'about/license'],
    },
    {
      type: 'autogenerated',
      dirName: '.', // Авто-генерация всех папок в docs/
    },
  ],
};

export default sidebars;