// sidebars.js
const sidebars = {
  docsSidebar: [
    {
      type: 'category',
      label: '🧩 О проекте',
      items: [
        'about/contact',
        'about/license',
      ],
    },
    {
      type: 'autogenerated',
      dirName: '.', // Автоматически добавит все папки, кроме .about
    },
  ],
};

export default sidebars;