/** Метаданные языков для курсов (дети, новички, преподаватели). */

export const TEACHING_LANGUAGES = [
  {
    id: 'scratch',
    label: 'Scratch',
    icon: '🐱',
    color: '#ffab19',
    paradigm: 'Блоки (визуальный)',
    execution: 'Интерпретатор в браузере',
    memory: 'Автоматически (скрыто)',
    typing: 'Динамическая (без явных типов)',
    ageFrom: 8,
    difficulty: 1,
    bestFor: 'Первый алгоритм: циклы, ветвления, спрайты, истории и мини-игры.',
    metaphor: 'Конструктор LEGO — блоки щёлкаются, порядок виден сразу.',
    firstLine: 'когда 🚩 нажат → сказать «Привет!»',
    pitfalls: [
      'Scratch — не «настоящий» текстовый код; переход на Java/C# нужно объяснить заранее.',
      'Имена спрайтов и переменных лучше давать по-русски или по-английски, но не смешивать в одном проекте.',
    ],
    articlePath: '/encyclopedia/9-spinoff/9-11-dlya-detey/5-kod/intro',
    firstProgramLang: null,
    compileBadge: 'Без компиляции',
    ecosystem: 'scratch.mit.edu, ScratchJr, TurboWarp',
  },
  {
    id: 'java',
    label: 'Java',
    icon: '☕',
    color: '#5382a1',
    paradigm: 'ООП, статическая типизация',
    execution: 'Компиляция в байт-код → JVM',
    memory: 'Сборщик мусора (GC)',
    typing: 'Статическая, явная',
    ageFrom: 11,
    difficulty: 3,
    bestFor: 'Школьные олимпиады, Android (исторически), корпоративный бэкенд, строгая дисциплина типов.',
    metaphor: 'Университет с правилами: сначала объявил класс — потом действуешь.',
    firstLine: 'System.out.println("Привет!");',
    pitfalls: [
      'Нужен класс с public static void main — нельзя начать с одной строки в файле.',
      'Java ≠ JavaScript — разные языки, путаница у родителей и учеников.',
    ],
    articlePath: '/encyclopedia/5-languages/5-03-java/1',
    firstProgramLang: 'java',
    compileBadge: 'Компиляция + JVM',
    ecosystem: 'JDK, Maven/Gradle, Spring, Android Studio',
  },
  {
    id: 'csharp',
    label: 'C#',
    icon: '🎮',
    color: '#68217a',
    paradigm: 'ООП, статическая типизация',
    execution: 'Компиляция в IL → .NET Runtime',
    memory: 'Сборщик мусора (GC)',
    typing: 'Статическая, явная',
    ageFrom: 11,
    difficulty: 3,
    bestFor: 'Unity-игры, Windows-приложения, корпоративный .NET, знакомый синтаксис после Java.',
    metaphor: 'Мастерская Microsoft: много готовых инструментов в одной коробке (.NET).',
    firstLine: 'Console.WriteLine("Привет!");',
    pitfalls: [
      'Точка с запятой обязательна; фигурные скобки — стиль блока кода.',
      'Версии .NET (6, 8…) — на уроке зафиксируйте одну LTS.',
    ],
    articlePath: '/encyclopedia/5-languages/5-05-csharp/1',
    firstProgramLang: 'csharp',
    compileBadge: 'Компиляция + .NET',
    ecosystem: 'Visual Studio, Rider, Unity, ASP.NET',
  },
  {
    id: 'kotlin',
    label: 'Kotlin',
    icon: '🤖',
    color: '#7f52ff',
    paradigm: 'ООП + функциональные элементы',
    execution: 'JVM / Native / JS (Kotlin Multiplatform)',
    memory: 'GC на JVM (как Java)',
    typing: 'Статическая, вывод типов',
    ageFrom: 12,
    difficulty: 3,
    bestFor: 'Современный Android, лаконичный синтаксис после Java, мультиплатформа.',
    metaphor: 'Java, но короче запись — меньше «шума», больше смысла в строке.',
    firstLine: 'fun main() { println("Привет!") }',
    pitfalls: [
      'null-безопасность (?., ?:) — объясните после базовых типов.',
      'На JVM всё равно нужна среда Java — установите JDK вместе с Kotlin.',
    ],
    articlePath: '/encyclopedia/5-languages/5-09-kotlin/1',
    firstProgramLang: 'kotlin',
    compileBadge: 'Компиляция + JVM',
    ecosystem: 'IntelliJ IDEA, Android Studio, Ktor',
  },
  {
    id: 'go',
    label: 'Go',
    icon: '🐹',
    color: '#00add8',
    paradigm: 'Процедурный + интерфейсы',
    execution: 'Компиляция в один бинарник',
    memory: 'Сборщик мусора (GC)',
    typing: 'Статическая, простая',
    ageFrom: 13,
    difficulty: 3,
    bestFor: 'Сервисы, DevOps-утилиты, когда нужен быстрый старт без тяжёлого ООП.',
    metaphor: 'Швейцарский нож: мало ключевых слов, всё по делу.',
    firstLine: 'fmt.Println("Привет!")',
    pitfalls: [
      'Ошибки возвращают как значения (if err != nil) — отдельный урок.',
      'Форматирование gofmt обязательно — покажите «go fmt» на уроке.',
    ],
    articlePath: '/encyclopedia/5-languages/5-10-go/1',
    firstProgramLang: 'go',
    compileBadge: 'Нативная компиляция',
    ecosystem: 'go mod, Docker, Kubernetes, microservices',
  },
  {
    id: 'cpp',
    label: 'C++',
    icon: '⚙️',
    color: '#00599c',
    paradigm: 'Мультипарадигменный, ООП',
    execution: 'Компиляция в машинный код',
    memory: 'Ручное + RAII (умные указатели)',
    typing: 'Статическая, строгая',
    ageFrom: 14,
    difficulty: 5,
    bestFor: 'Игры (Unreal), embedded, высокая производительность, олимпиады по информатике.',
    metaphor: 'Гоночный болид — мощно, но каждая деталь на совести водителя.',
    firstLine: 'std::cout << "Привет!" << std::endl;',
    pitfalls: [
      'Указатели и неопределённое поведение — не для первого месяца.',
      'Заголовки .h и линковка пугают новичков — начните с одного main.cpp.',
    ],
    articlePath: '/encyclopedia/5-languages/5-06-cpp/1',
    firstProgramLang: 'cpp',
    compileBadge: 'Нативная компиляция',
    ecosystem: 'CMake, Qt, Unreal, STL',
  },
  {
    id: 'rust',
    label: 'Rust',
    icon: '🦀',
    color: '#dea584',
    paradigm: 'Системный, владение (ownership)',
    execution: 'Компиляция в машинный код',
    memory: 'Владение и заимствование (без GC)',
    typing: 'Статическая, вывод типов',
    ageFrom: 15,
    difficulty: 5,
    bestFor: 'Безопасный системный код, WebAssembly, когда C++ кажется слишком хрупким.',
    metaphor: 'Охранник у двери памяти — компилятор не пустит, пока данные «не сданы».',
    firstLine: 'println!("Привет!");',
    pitfalls: [
      'Borrow checker — нормально, что первые недели много ошибок компиляции.',
      'async/await и макросы — оставьте на продвинутый курс.',
    ],
    articlePath: '/encyclopedia/5-languages/5-13-rust/1',
    firstProgramLang: 'rust',
    compileBadge: 'Нативная компиляция',
    ecosystem: 'cargo, crates.io, embedded, WASM',
  },
];

/** Рекомендуемая лестница для курса (можно менять под класс). */
export const TEACHING_LADDER = [
  {step: 1, id: 'scratch', label: 'Scratch', note: 'Алгоритмы без синтаксиса'},
  {step: 2, id: 'kotlin', label: 'Kotlin или Java', note: 'Первый текстовый ООП'},
  {step: 3, id: 'csharp', label: 'C#', note: 'Игры Unity / .NET'},
  {step: 4, id: 'go', label: 'Go', note: 'Сервисы и утилиты'},
  {step: 5, id: 'cpp', label: 'C++', note: 'Производительность и железо'},
  {step: 6, id: 'rust', label: 'Rust', note: 'Безопасность памяти'},
];

export const TEACHING_COMPARE_ROWS = [
  {
    id: 'hello',
    label: 'Привет, мир',
    hint: 'Минимальная программа — вывод текста.',
    scratch: 'когда 🚩 нажат\n  сказать «Привет!»',
    java: 'System.out.println("Привет!");',
    csharp: 'Console.WriteLine("Привет!");',
    kotlin: 'println("Привет!")',
    go: 'fmt.Println("Привет!")',
    cpp: 'std::cout << "Привет!" << std::endl;',
    rust: 'println!("Привет!");',
  },
  {
    id: 'var',
    label: 'Переменная',
    hint: 'Имя для значения, которое можно менять.',
    scratch: 'задать [счёт] в (0)\nизменить [счёт] на (1)',
    java: 'int score = 0;\nscore = 1;',
    csharp: 'int score = 0;\nscore = 1;',
    kotlin: 'var score = 0\nscore = 1',
    go: 'score := 0\nscore = 1',
    cpp: 'int score = 0;\nscore = 1;',
    rust: 'let mut score = 0;\nscore = 1;',
  },
  {
    id: 'if',
    label: 'Условие',
    hint: 'Выполнить ветку только если условие истинно.',
    scratch: 'если <(счёт) > [50]> то\n  сказать «Сдал»',
    java: 'if (score >= 50) {\n  System.out.println("Сдал");\n}',
    csharp: 'if (score >= 50) {\n  Console.WriteLine("Сдал");\n}',
    kotlin: 'if (score >= 50) {\n    println("Сдал")\n}',
    go: 'if score >= 50 {\n  fmt.Println("Сдал")\n}',
    cpp: 'if (score >= 50) {\n  std::cout << "Сдал";\n}',
    rust: 'if score >= 50 {\n  println!("Сдал");\n}',
  },
  {
    id: 'loop',
    label: 'Цикл',
    hint: 'Повторить действие несколько раз.',
    scratch: 'повторить (3) раз\n  идти (10) шагов',
    java: 'for (int i = 0; i < 3; i++) {\n  System.out.println(i);\n}',
    csharp: 'for (int i = 0; i < 3; i++) {\n  Console.WriteLine(i);\n}',
    kotlin: 'for (i in 0 until 3) {\n    println(i)\n}',
    go: 'for i := 0; i < 3; i++ {\n  fmt.Println(i)\n}',
    cpp: 'for (int i = 0; i < 3; i++) {\n  std::cout << i;\n}',
    rust: 'for i in 0..3 {\n  println!("{i}");\n}',
  },
  {
    id: 'func',
    label: 'Функция / метод',
    hint: 'Именованный блок кода, который можно вызывать.',
    scratch: 'определить [привет]\n  сказать «Привет!»',
    java: 'static void greet() {\n  System.out.println("Привет!");\n}',
    csharp: 'static void Greet() {\n  Console.WriteLine("Привет!");\n}',
    kotlin: 'fun greet() {\n  println("Привет!")\n}',
    go: 'func greet() {\n  fmt.Println("Привет!")\n}',
    cpp: 'void greet() {\n  std::cout << "Привет!";\n}',
    rust: 'fn greet() {\n  println!("Привет!");\n}',
  },
];

export const MEMORY_MODEL_SCENARIOS = [
  {
    id: 'gc',
    title: 'Сборщик мусора (Java, C#, Kotlin, Go)',
    langs: ['java', 'csharp', 'kotlin', 'go'],
    steps: [
      'Создали объект в куче — ссылка в переменной.',
      'Ссылки больше нет — объект «мусор».',
      'GC в фоне освобождает память (пауза возможна).',
    ],
    teacherTip: 'На уроке: «память убирает уборщик, не ученик» — меньше страха, но непредсказуемые паузы.',
  },
  {
    id: 'manual',
    title: 'Ручное управление (C++)',
    langs: ['cpp'],
    steps: [
      'new выделяет память — вы отвечаете за delete.',
      'Забыли delete → утечка памяти.',
      'Лишний delete → падение программы.',
    ],
    teacherTip: 'Покажите std::unique_ptr раньше, чем сырой new/delete — современный C++ для курса.',
  },
  {
    id: 'ownership',
    title: 'Владение (Rust)',
    langs: ['rust'],
    steps: [
      'У значения один владелец — при присваивании владение переходит.',
      'Заимствование (&) — читать можно, пока никто не владеет.',
      'Компилятор не даст использовать память после move.',
    ],
    teacherTip: 'Ошибки borrow checker — не «ученик плохой», а тренажёр безопасности до запуска.',
  },
];

export const DEFAULT_COMPARE_LANGS = ['scratch', 'java', 'csharp', 'kotlin'];
