import React, { useState } from 'react';
import BrowserOnly from '@docusaurus/BrowserOnly';

const CodeTransformationDemo = () => {
  const [selectedExample, setSelectedExample] = useState('java');
  const [activeView, setActiveView] = useState('source');

  const examples = {
    java: {
      name: 'Java',
      icon: '☕',
      sourceCode: `public class Main {
    public static void main(String[] args) {
        System.out.println("Hello World");
    }
}`,
      byteCode: `// Java bytecode (javap -c Main.class)
public class Main {
  public Main();
    Code:
       0: aload_0
       1: invokespecial #1
       4: return

  public static void main(java.lang.String[]);
    Code:
       0: getstatic     #2
       3: ldc           #3
       5: invokevirtual #4
       8: return
}`,
      machineCode: `// x86-64 assembly (JIT compiled)
main:
    push    rbp
    mov     rbp, rsp
    sub     rsp, 32
    mov     DWORD PTR [rbp-4], edi
    mov     QWORD PTR [rbp-16], rsi
    mov     edi, OFFSET FLAT:.LC0
    call    puts
    mov     eax, 0
    leave
    ret

.LC0:
    .string "Hello World"`
    },
    python: {
      name: 'Python',
      icon: '🐍',
      sourceCode: `def main():
    print("Hello World")

if __name__ == "__main__":
    main()`,
      byteCode: `// Python bytecode (dis.dis)
  1           0 LOAD_CONST               0 (<code object main>)
              2 LOAD_CONST               1 ('main')
              4 MAKE_FUNCTION            0
              6 STORE_NAME               0 (main)

  4           8 LOAD_NAME                1 (__name__)
             10 LOAD_CONST               2 ('__main__')
             12 COMPARE_OP               2 (==)
             14 POP_JUMP_IF_FALSE       22

  5          16 LOAD_NAME                0 (main)
             18 CALL_FUNCTION            0
             20 POP_TOP
             22 LOAD_CONST               3 (None)
             24 RETURN_VALUE

// main function bytecode:
  2           0 LOAD_GLOBAL              0 (print)
              2 LOAD_CONST               1 ('Hello World')
              4 CALL_FUNCTION            1
              6 POP_TOP
              8 LOAD_CONST               0 (None)
             10 RETURN_VALUE`,
      machineCode: `// CPython VM interpretation (simplified)
// Python VM reads bytecode and executes C functions:

case TARGET(LOAD_CONST): {
    PyObject *value = GETITEM(consts, oparg);
    PUSH(value);
    Py_INCREF(value);
    DISPATCH();
}

case TARGET(CALL_FUNCTION): {
    PyObject **sp_stack = stack_pointer;
    PyObject *callable = PEEK(oparg);
    PyObject *result = call_function(&sp_stack, oparg, NULL);
    stack_pointer = sp_stack;
    SET_TOP(result);
    DISPATCH();
}`
    },
    csharp: {
      name: 'C#',
      icon: '🔷',
      sourceCode: `using System;

class Program {
    static void Main() {
        Console.WriteLine("Hello World");
    }
}`,
      byteCode: `// CIL (Common Intermediate Language) - .NET bytecode
.method private hidebysig static void Main() cil managed
{
    .entrypoint
    .maxstack 8
    
    IL_0000: nop
    IL_0001: ldstr      "Hello World"
    IL_0006: call       void [mscorlib]System.Console::WriteLine(string)
    IL_000b: nop
    IL_000c: ret
}`,
      machineCode: `// x86-64 assembly (JIT compiled by RyuJIT)
; Method Program:Main()
G_M197_IG01:
    55                   push     rbp
    4883EC20             sub      rsp, 32
    488D6C2420           lea      rbp, [rsp+20H]

G_M197_IG02:
    48B9603B4D4FBC7F0000 mov      rcx, 0x7FBC4F4D3B60
    E8E3A0C75F           call     System.Console:WriteLine(System.String)

G_M197_IG03:
    90                   nop
    4883C420             add      rsp, 32
    5D                   pop      rbp
    C3                   ret`
    },
    javascript: {
      name: 'JavaScript',
      icon: '🟨',
      sourceCode: `function main() {
    console.log("Hello World");
}

main();`,
      byteCode: `// V8 bytecode (Ignition interpreter)
[generated bytecode for function: main]
Parameter count 1
Frame size 8
   0x2d9a0012a2be @   0 : 12 00       LdaConstant [0]
   0x2d9a0012a2c0 @   2 : 26 f8       Star r1
   0x2d9a0012a2c2 @   4 : 13 01 00    LdaGlobal [1], [0]
   0x2d9a0012a2c5 @   7 : 26 f9       Star r0
   0x2d9a0012a2c7 @   9 : 28 f9 01    LdaNamedProperty r0, [1], [1]
   0x2d9a0012a2ca @  12 : 26 f8       Star r1
   0x2d9a0012a2cc @  14 : 12 02       LdaConstant [2]
   0x2d9a0012a2ce @  16 : 26 f6       Star r3
   0x2d9a0012a2d0 @  18 : 0c 03       CallNoFeedback [3]
   0x2d9a0012a2d2 @  20 : 26 f6       Star r3
   0x2d9a0012a2d4 @  22 : 0d          LdaUndefined
   0x2d9a0012a2d5 @  23 : a8          Return`,
      machineCode: `// x86-64 assembly (JIT compiled by TurboFan)
// Optimized machine code for main()
0x2d9a0012a301   0  55                     push rbp
0x2d9a0012a302   1  4889e5                 mov rbp, rsp
0x2d9a0012a305   4  56                     push rsi
0x2d9a0012a306   5  57                     push rdi
0x2d9a0012a307   6  4883ec08               sub rsp, 0x8
0x2d9a0012a30b  10  488b47ff               mov rax, [rdi-0x1]
0x2d9a0012a30f  14  48bf286b95b20b000000   mov rdi, 0xbb2956b28
0x2d9a0012a319  24  e8c2d2b0d7             call 0x1e3a53075e0  (String::Print)
0x2d9a0012a31e  29  4883c408               add rsp, 0x8
0x2d9a0012a322  33  5f                     pop rdi
0x2d9a0012a323  34  5e                     pop rsi
0x2d9a0012a324  35  5d                     pop rbp
0x2d9a0012a325  36  c3                     ret`
    }
  };

  const currentExample = examples[selectedExample];

  const getViewTitle = () => {
    switch(activeView) {
      case 'source': return '📝 Исходный код (для программиста)';
      case 'bytecode': return '🔩 Промежуточный код / Байт-код (для виртуальной машины)';
      case 'machine': return '💻 Машинный код (для процессора)';
      default: return '';
    }
  };

  const getViewIcon = () => {
    switch(activeView) {
      case 'source': return '📝';
      case 'bytecode': return '🔩';
      case 'machine': return '💻';
      default: return '';
    }
  };

  return (
    <div style={{
      border: '1px solid #e1e4e8',
      borderRadius: '12px',
      padding: '16px',
      maxWidth: '100%',
      width: '100%',
      margin: '0 auto',
      fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif',
      backgroundColor: '#ffffff',
      boxShadow: '0 2px 8px rgba(0,0,0,0.08)',
      boxSizing: 'border-box'
    }}>
      <h3 style={{ 
        marginTop: 0, 
        marginBottom: '8px', 
        color: '#24292e', 
        fontSize: 'clamp(18px, 5vw, 20px)' 
      }}>
        🔄 Трансформация кода
      </h3>
      <p style={{ 
        marginBottom: '20px', 
        color: '#586069', 
        fontSize: 'clamp(12px, 4vw, 14px)' 
      }}>
        Как один и тот же код выглядит на разных уровнях абстракции
      </p>

      {/* Выбор языка - горизонтальный скролл на мобильных */}
      <div style={{
        marginBottom: '20px',
        display: 'flex',
        gap: '8px',
        flexWrap: 'wrap',
        borderBottom: '1px solid #e1e4e8',
        paddingBottom: '12px',
        overflowX: 'auto',
        WebkitOverflowScrolling: 'touch'
      }}>
        {Object.entries(examples).map(([key, lang]) => (
          <button
            key={key}
            onClick={() => {
              setSelectedExample(key);
              setActiveView('source');
            }}
            style={{
              padding: '6px 12px',
              borderRadius: '20px',
              border: selectedExample === key ? '2px solid #0366d6' : '1px solid #d1d5da',
              backgroundColor: selectedExample === key ? '#f1f8ff' : '#ffffff',
              color: selectedExample === key ? '#0366d6' : '#586069',
              cursor: 'pointer',
              fontWeight: '500',
              fontSize: 'clamp(12px, 3.5vw, 14px)',
              display: 'flex',
              alignItems: 'center',
              gap: '4px',
              whiteSpace: 'nowrap',
              flexShrink: 0,
              transition: 'all 0.2s ease'
            }}
          >
            <span style={{ fontSize: 'clamp(14px, 4vw, 16px)' }}>{lang.icon}</span> 
            <span>{lang.name}</span>
          </button>
        ))}
      </div>

      {/* Уровни просмотра - вертикальная раскладка на мобильных */}
      <div style={{
        marginBottom: '20px',
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        backgroundColor: '#f6f8fa',
        padding: '8px',
        borderRadius: '8px'
      }}>
        <button
          onClick={() => setActiveView('source')}
          style={{
            padding: '10px',
            borderRadius: '6px',
            border: 'none',
            backgroundColor: activeView === 'source' ? '#ffffff' : 'transparent',
            color: activeView === 'source' ? '#24292e' : '#586069',
            cursor: 'pointer',
            fontWeight: activeView === 'source' ? '600' : '400',
            fontSize: 'clamp(13px, 3.5vw, 14px)',
            boxShadow: activeView === 'source' ? '0 1px 3px rgba(0,0,0,0.12)' : 'none',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            gap: '8px',
            transition: 'all 0.2s ease'
          }}
        >
          <span style={{ fontSize: 'clamp(16px, 4vw, 18px)' }}>📝</span> 
          <span>Исходный код</span>
        </button>
        <button
          onClick={() => setActiveView('bytecode')}
          style={{
            padding: '10px',
            borderRadius: '6px',
            border: 'none',
            backgroundColor: activeView === 'bytecode' ? '#ffffff' : 'transparent',
            color: activeView === 'bytecode' ? '#24292e' : '#586069',
            cursor: 'pointer',
            fontWeight: activeView === 'bytecode' ? '600' : '400',
            fontSize: 'clamp(13px, 3.5vw, 14px)',
            boxShadow: activeView === 'bytecode' ? '0 1px 3px rgba(0,0,0,0.12)' : 'none',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            gap: '8px',
            transition: 'all 0.2s ease'
          }}
        >
          <span style={{ fontSize: 'clamp(16px, 4vw, 18px)' }}>🔩</span> 
          <span>Байт-код / Промежуточный</span>
        </button>
        <button
          onClick={() => setActiveView('machine')}
          style={{
            padding: '10px',
            borderRadius: '6px',
            border: 'none',
            backgroundColor: activeView === 'machine' ? '#ffffff' : 'transparent',
            color: activeView === 'machine' ? '#24292e' : '#586069',
            cursor: 'pointer',
            fontWeight: activeView === 'machine' ? '600' : '400',
            fontSize: 'clamp(13px, 3.5vw, 14px)',
            boxShadow: activeView === 'machine' ? '0 1px 3px rgba(0,0,0,0.12)' : 'none',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            gap: '8px',
            transition: 'all 0.2s ease'
          }}
        >
          <span style={{ fontSize: 'clamp(16px, 4vw, 18px)' }}>💻</span> 
          <span>Машинный код / Ассемблер</span>
        </button>
      </div>

      {/* Заголовок текущего вида */}
      <div style={{
        marginBottom: '12px',
        padding: '8px 12px',
        backgroundColor: '#f6f8fa',
        borderRadius: '6px',
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        flexWrap: 'wrap'
      }}>
        <span style={{ fontSize: 'clamp(18px, 5vw, 20px)' }}>{getViewIcon()}</span>
        <span style={{ 
          fontWeight: '600', 
          color: '#24292e', 
          fontSize: 'clamp(12px, 3.5vw, 14px)' 
        }}>
          {getViewTitle()}
        </span>
      </div>

      {/* Отображение кода с горизонтальным скроллом */}
      <div style={{
        backgroundColor: '#f6f8fa',
        borderRadius: '8px',
        overflow: 'hidden',
        border: '1px solid #e1e4e8',
        marginBottom: '20px'
      }}>
        <div style={{
          backgroundColor: '#24292e',
          color: '#e1e4e8',
          padding: '8px 16px',
          fontSize: 'clamp(10px, 3vw, 12px)',
          fontFamily: 'monospace',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          flexWrap: 'wrap',
          gap: '8px'
        }}>
          <span>
            {currentExample.name} {activeView === 'source' && 'source code'}
            {activeView === 'bytecode' && ' bytecode'}
            {activeView === 'machine' && ' machine code'}
          </span>
          <span style={{ fontSize: 'clamp(9px, 2.5vw, 11px)', opacity: 0.7 }}>
            {activeView === 'source' && '👨‍💻 Для разработчиков'}
            {activeView === 'bytecode' && '⚙️ Для виртуальной машины'}
            {activeView === 'machine' && '🔌 Для процессора'}
          </span>
        </div>
        <pre style={{
          margin: 0,
          padding: '16px',
          overflowX: 'auto',
          overflowY: 'auto',
          fontSize: 'clamp(10px, 3vw, 12px)',
          fontFamily: 'Consolas, "Courier New", monospace',
          lineHeight: '1.5',
          backgroundColor: '#ffffff',
          WebkitOverflowScrolling: 'touch',
          maxHeight: '400px'
        }}>
          {activeView === 'source' && currentExample.sourceCode}
          {activeView === 'bytecode' && currentExample.byteCode}
          {activeView === 'machine' && currentExample.machineCode}
        </pre>
      </div>

      {/* Объяснение */}
      <div style={{
        backgroundColor: '#f1f8ff',
        borderLeft: '4px solid #0366d6',
        padding: '16px',
        borderRadius: '6px',
        marginTop: '16px'
      }}>
        <div style={{ 
          fontWeight: '600', 
          marginBottom: '8px', 
          color: '#0366d6', 
          fontSize: 'clamp(13px, 3.5vw, 14px)' 
        }}>
          💡 Что здесь происходит?
        </div>
        <div style={{ 
          fontSize: 'clamp(12px, 3.5vw, 13px)', 
          color: '#24292e', 
          lineHeight: '1.6' 
        }}>
          {activeView === 'source' && (
            <>
              <strong>Исходный код</strong> — это текст, который пишет программист на языке высокого уровня 
              (Java, Python, C# и т.д.). Он понятен человеку, но не понятен компьютеру. 
              Программист использует синтаксис языка, переменные, функции и другие абстракции для удобства разработки.
            </>
          )}
          {activeView === 'bytecode' && (
            <>
              <strong>Байт-код / Промежуточный код</strong> — это результат компиляции исходного кода. 
              Он не выполняется напрямую процессором, а предназначен для виртуальной машины (JVM, CLR, V8 и т.д.).
              Байт-код является компромиссом: он компактнее исходного кода, но при этом платформонезависим.
              Виртуальная машина либо интерпретирует его, либо компилирует дальше в машинный код (JIT-компиляция).
            </>
          )}
          {activeView === 'machine' && (
            <>
              <strong>Машинный код / Ассемблер</strong> — это команды, которые непосредственно понимает 
              процессор. В этом коде уже нет абстракций: только операции с регистрами, памятью и стеком.
              Машинный код зависит от архитектуры процессора (x86, ARM и т.д.). Именно его выполняет железо.
              JIT-компилятор переводит байт-код в машинный код во время выполнения программы для максимальной производительности.
            </>
          )}
        </div>
      </div>

      {/* Сравнительная таблица - горизонтальный скролл на мобильных */}
      <div style={{
        marginTop: '20px',
        overflowX: 'auto',
        fontSize: 'clamp(11px, 3vw, 13px)',
        WebkitOverflowScrolling: 'touch'
      }}>
        <table style={{
          width: '100%',
          minWidth: '500px',
          borderCollapse: 'collapse',
          backgroundColor: '#ffffff',
          border: '1px solid #e1e4e8'
        }}>
          <thead>
            <tr style={{ backgroundColor: '#f6f8fa', borderBottom: '1px solid #e1e4e8' }}>
              <th style={{ padding: '10px', textAlign: 'left' }}>Характеристика</th>
              <th style={{ padding: '10px', textAlign: 'left' }}>Исходный код</th>
              <th style={{ padding: '10px', textAlign: 'left' }}>Байт-код</th>
              <th style={{ padding: '10px', textAlign: 'left' }}>Машинный код</th>
            </tr>
          </thead>
          <tbody>
            <tr style={{ borderBottom: '1px solid #e1e4e8' }}>
              <td style={{ padding: '10px', fontWeight: '600' }}>Предназначен для</td>
              <td style={{ padding: '10px' }}>Программиста</td>
              <td style={{ padding: '10px' }}>Виртуальной машины</td>
              <td style={{ padding: '10px' }}>Процессора</td>
            </tr>
            <tr style={{ borderBottom: '1px solid #e1e4e8' }}>
              <td style={{ padding: '10px', fontWeight: '600' }}>Уровень абстракции</td>
              <td style={{ padding: '10px' }}>Высокий</td>
              <td style={{ padding: '10px' }}>Средний</td>
              <td style={{ padding: '10px' }}>Низкий</td>
            </tr>
            <tr style={{ borderBottom: '1px solid #e1e4e8' }}>
              <td style={{ padding: '10px', fontWeight: '600' }}>Читаемость для человека</td>
              <td style={{ padding: '10px' }}>Отличная</td>
              <td style={{ padding: '10px' }}>Средняя</td>
              <td style={{ padding: '10px' }}>Сложная</td>
            </tr>
            <tr>
              <td style={{ padding: '10px', fontWeight: '600' }}>Зависимость от платформы</td>
              <td style={{ padding: '10px' }}>Не зависит (обычно)</td>
              <td style={{ padding: '10px' }}>Не зависит (спецификация VM)</td>
              <td style={{ padding: '10px' }}>Полная зависимость</td>
            </tr>
          </tbody>
        </table>
      </div>
      
      {/* Добавляем медиа-запрос через style injection для десктопов */}
      <style>{`
        @media (min-width: 768px) {
          div[style*="flex-direction: column"] {
            flex-direction: row !important;
          }
        }
      `}</style>
    </div>
  );
};

// Экспортируем компонент с тем же именем, чтобы старые импорты работали
export default CodeTransformationDemo;